# Appendix: DownSampling

To better train the model, we select the same number of positive and negative cases.

In [3]:
%matplotlib inline
import random
import datetime
import pandas as pd
import matplotlib.pyplot as plt
import statistics
import numpy as np
import scipy
from scipy import stats
import seaborn as sns

In [4]:
train = pd.read_csv('kaggle/train.csv')

The number of is_booking = True is just around 8% of all sample, which are miniority

In [5]:
train["is_booking"].value_counts(normalize=True)

0    0.920343
1    0.079657
Name: is_booking, dtype: float64

In [6]:
train["is_booking"].value_counts(normalize=False)

0    34669600
1     3000693
Name: is_booking, dtype: int64

We are going to pick 80000 positive and 80000 negative cases for training

In [7]:
TARGET_CNT = 80000

from sklearn.utils import resample

train_majority = train[train.is_booking==0]
train_minority = train[train.is_booking==1]

df_majority_downsampled = resample(train_majority, 
                                 replace=False,    # sample without replacement
                                 n_samples=TARGET_CNT,     # to match minority class
                                 random_state=123) # reproducible results


df_minority_downsampled = resample(train_minority, 
                                 replace=False,    # sample without replacement
                                 n_samples=TARGET_CNT,     # to match minority class
                                 random_state=123) # reproducible results

df_downsampled = pd.concat([df_majority_downsampled, df_minority_downsampled])

Checking output and export the file

In [8]:
df_downsampled.is_booking.value_counts()

0    80000
1    80000
Name: is_booking, dtype: int64

In [8]:
df_downsampled.to_csv("train_ds.csv", index=False)

In [9]:
df_downsampled

,date_time,site_name,posa_continent,user_location_country,user_location_region,user_location_city,orig_destination_distance,user_id,is_mobile,is_package,...,srch_children_cnt,srch_rm_cnt,srch_destination_id,srch_destination_type_id,is_booking,cnt,hotel_continent,hotel_country,hotel_market,hotel_cluster
7259861,2013-03-25 16:12:06,2,3,66,447,902,364.8075,895388,0,0,...,0,1,44148,6,0,1,2,50,1309,7
30230947,2014-09-24 12:02:43,24,2,3,50,5224,NaN,12756,0,0,...,0,2,60986,4,0,1,6,46,1089,44
18737554,2014-07-09 13:39:10,2,3,66,294,3688,523.5604,327568,0,1,...,0,1,44253,8,0,3,2,50,682,84
7531922,2014-10-26 05:23:29,2,3,66,348,48862,8721.3494,461790,0,0,...,2,1,21222,1,0,1,3,152,73,27
15012088,2014-06-11 11:08:55,2,3,66,220,5444,2397.7515,270101,0,0,...,0,1,8279,1,0,1,2,50,1230,69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1071074,2014-12-02 20:39:26,2,3,66,174,5938,2443.2904,1088629,1,0,...,1,1,12236,6,1,1,2,50,676,33
30776410,2013-11-11 19:47:09,37,1,69,727,48073,NaN,213616,0,0,...,0,2,18481,1,1,1,6,70,309,28
16284830,2014-04-08 17:23:25,2,3,66,311,16159,66.1271,52964,0,0,...,2,2,8846,1,1,1,2,50,691,55
11340090,2014-03-17 18:26:14,11,3,205,354,27869,128.0394,397588,0,0,...,1,1,25928,1,1,1,2,198,379,42
16362306,2014-09-09 21:09:10,34,3,205,135,36086,1014.2068,255978,0,0,...,0,1,12826,5,1,1,2,50,1230,77

In [9]:
train[train["cnt"] > 10]["user_id"].value_counts()

89617      16
1096979    16
203937     14
655945     14
693247     14
           ..
724729      1
724753      1
724852      1
727299      1
1196406     1
Name: user_id, Length: 59911, dtype: int64

In [10]:
train[(train["user_id"] == 89617) & (train["hotel_country"] == 8)]

,date_time,site_name,posa_continent,user_location_country,user_location_region,user_location_city,orig_destination_distance,user_id,is_mobile,is_package,...,srch_children_cnt,srch_rm_cnt,srch_destination_id,srch_destination_type_id,is_booking,cnt,hotel_continent,hotel_country,hotel_market,hotel_cluster
30736558,2014-02-26 18:53:51,2,3,66,442,7145,1038.8100,89617,0,1,...,0,1,11938,1,0,3,4,8,126,44
30736559,2014-02-26 18:55:05,2,3,66,442,7145,1033.3106,89617,0,1,...,0,1,11938,1,0,4,4,8,126,66
30736560,2014-02-26 18:56:12,2,3,66,442,7145,1031.7249,89617,0,1,...,0,1,11938,1,0,3,4,8,126,66
30736561,2014-02-26 19:15:08,2,3,66,442,7145,1009.3771,89617,0,1,...,0,1,33919,6,0,15,4,8,110,66
30736562,2014-02-27 05:01:34,2,3,66,442,7145,1009.3771,89617,0,1,...,0,1,33919,6,0,1,4,8,110,66
30736563,2014-02-27 05:02:35,2,3,66,442,7145,1009.3771,89617,0,1,...,0,1,8791,1,0,1,4,8,110,66
30736564,2014-02-27 05:16:21,2,3,66,442,7145,1009.3771,89617,0,1,...,0,1,8791,1,0,8,4,8,110,66
30736565,2014-02-27 05:19:02,2,3,66,442,7145,1009.1982,89617,0,1,...,0,1,8791,1,0,52,4,8,110,66
30736566,2014-02-27 05:46:20,2,3,66,442,7145,1009.3771,89617,0,0,...,0,1,8791,1,0,1,4,8,110,66
30736567,2014-02-27 05:51:13,2,3,66,442,7145,1009.1982,89617,0,0,...,0,1,8791,1,0,2,4,8,110,66
30736568,2014-02-27 07:42:58,2,3,66,442,7145,1017.7846,89617,0,1,...,0,1,8791,1,0,15,4,8,110,66
30736569,2014-02-27 07:47:42,2,3,66,442,7145,1018.5009,89617,0,1,...,0,1,8791,1,0,16,4,8,110,66
30736570,2014-02-27 07:54:00,2,3,66,442,7145,1009.1982,89617,0,1,...,0,1,8791,1,0,23,4,8,110,66
30736571,2014-02-27 07:55:43,2,3,66,442,7145,1009.3771,89617,0,1,...,0,1,8791,1,0,8,4,8,110,66
30736572,2014-02-28 03:45:35,2,3,66,442,7145,1021.4491,89617,0,1,...,0,1,8791,1,0,3,4,8,110,52
30736573,2014-02-28 03:47:16,2,3,66,442,7145,1009.1982,89617,0,1,...,0,1,8791,1,0,10,4,8,110,66
30736574,2014-02-28 04:49:26,2,3,66,442,7145,1009.1982,89617,0,1,...,0,1,8791,1,1,1,4,8,110,66
30736575,2014-03-03 12:55:47,2,3,66,442,7145,1009.1982,89617,0,1,...,0,1,8791,1,0,2,4,8,110,66
30736576,2014-03-04 06:12:38,2,3,66,442,7145,1077.7010,89617,0,1,...,0,1,8824,1,0,5,4,8,118,66
30736577,2014-03-04 06:13:12,2,3,66,442,7145,1074.3297,89617,0,1,...,0,1,8824,1,0,5,4,8,118,65
30736578,2014-03-04 06:13:44,2,3,66,442,7145,1065.4488,89617,0,1,...,0,1,8824,1,0,12,4,8,118,52
30736579,2014-03-04 06:15:54,2,3,66,442,7145,1055.7345,89617,0,1,...,0,1,8824,1,0,12,4,8,118,66
30736580,2014-03-04 06:17:33,2,3,66,442,7145,1065.0439,89617,0,1,...,0,1,8824,1,0,6,4,8,118,89
30736581,2014-03-06 16:37:30,2,3,66,442,7145,1065.0439,89617,0,1,...,0,1,8824,1,0,16,4,8,118,89
30736582,2014-03-06 16:43:18,2,3,66,442,7145,1055.7345,89617,0,1,...,0,1,8824,1,0,11,4,8,118,66
30736591,2014-04-30 13:38:34,2,3,66,442,7145,1009.1982,89617,0,1,...,0,1,8791,1,0,2,4,8,110,66
30736592,2014-05-25 23:12:53,2,3,66,435,40631,1031.3105,89617,0,1,...,0,1,8791,1,0,2,4,8,110,66
30736593,2014-05-25 23:20:10,2,3,66,435,40631,1031.3105,89617,0,1,...,0,1,8791,1,0,2,4,8,110,66
30736594,2014-06-05 17:42:08,2,3,66,442,7145,1065.0439,89617,0,1,...,0,1,8824,1,0,2,4,8,118,89
30736595,2014-06-05 17:46:59,2,3,66,442,7145,1009.6184,89617,0,1,...,0,1,8810,1,0,14,4,8,1532,52
30736596,2014-06-05 17:54:22,2,3,66,442,7145,1010.8910,89617,0,1,...,0,1,8810,1,0,7,4,8,1532,66
30736612,2014-07-01 23:12:02,2,3,66,435,32320,1037.8570,89617,0,1,...,0,1,8791,1,0,1,4,8,110,0

# Normal Sampling

Keeping the distribution of both positive and negative case

In [11]:
n_downsample = resample(train,
                      replace=False,  
                      n_samples=TARGET_CNT*2,   
                      random_state=123)

In [12]:
n_downsample.to_csv("train_ds_n.csv", index=False)