# Exercise 9a - Basic operations with dataframe

Using the yfinance library to get Microsoft Stock data of past 5 years.

In [4]:
import pandas as pd
import yfinance as yf

# Get MSFT stock data for the last 5 years using history method
msft_ticker = yf.Ticker('MSFT')
msft = msft_ticker.history(period="5y")

In [5]:
msft

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-03-25 00:00:00-04:00,225.784364,227.358041,222.205211,222.944061,34061900,0.0,0.0
2021-03-26 00:00:00-04:00,222.186020,227.137350,222.186020,226.916641,25479900,0.0,0.0
2021-03-29 00:00:00-04:00,227.022219,227.223733,222.502701,225.726822,25227500,0.0,0.0
2021-03-30 00:00:00-04:00,224.085945,224.393011,221.754223,222.473892,24792000,0.0,0.0
2021-03-31 00:00:00-04:00,223.491071,229.430748,222.992096,226.235413,43623500,0.0,0.0
...,...,...,...,...,...,...,...
2026-03-18 00:00:00-04:00,397.130005,398.000000,391.000000,391.790009,25908500,0.0,0.0
2026-03-19 00:00:00-04:00,390.100006,392.489990,387.059998,389.019989,25138800,0.0,0.0
2026-03-20 00:00:00-04:00,386.790009,387.000000,380.119995,381.869995,50853200,0.0,0.0
2026-03-23 00:00:00-04:00,383.899994,387.209991,381.679993,383.000000,29680100,0.0,0.0
2026-03-24 00:00:00-04:00,382.410004,382.470001,371.850006,372.739990,40186581,0.0,0.0

Q1. List the Index

In [6]:
msft.index

DatetimeIndex(['2021-03-25 00:00:00-04:00', '2021-03-26 00:00:00-04:00',
               '2021-03-29 00:00:00-04:00', '2021-03-30 00:00:00-04:00',
               '2021-03-31 00:00:00-04:00', '2021-04-01 00:00:00-04:00',
               '2021-04-05 00:00:00-04:00', '2021-04-06 00:00:00-04:00',
               '2021-04-07 00:00:00-04:00', '2021-04-08 00:00:00-04:00',
               ...
               '2026-03-11 00:00:00-04:00', '2026-03-12 00:00:00-04:00',
               '2026-03-13 00:00:00-04:00', '2026-03-16 00:00:00-04:00',
               '2026-03-17 00:00:00-04:00', '2026-03-18 00:00:00-04:00',
               '2026-03-19 00:00:00-04:00', '2026-03-20 00:00:00-04:00',
               '2026-03-23 00:00:00-04:00', '2026-03-24 00:00:00-04:00'],
              dtype='datetime64[ns, America/New_York]', name='Date', length=1255, freq=None)

Q2. List the Columns Name

In [7]:
msft.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits'], dtype='object')

Q3. Filter the dataframe to get the data of 2024 only.

In [8]:
msft_2024 = msft.loc['2024']
msft_2024

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-01-02 00:00:00-05:00,367.528834,369.534296,360.558903,364.589478,25258600,0.0,0.0
2024-01-03 00:00:00-05:00,362.760996,366.939024,362.269463,364.324066,23083500,0.0,0.0
2024-01-04 00:00:00-05:00,364.392855,366.781697,360.952126,361.709076,20901500,0.0,0.0
2024-01-05 00:00:00-05:00,362.721649,365.759318,360.293477,361.522308,21004600,0.0,0.0
2024-01-08 00:00:00-05:00,363.046020,368.846130,362.760953,368.344757,23134000,0.0,0.0
...,...,...,...,...,...,...,...
2024-12-24 00:00:00-05:00,430.484578,435.387152,430.028995,435.119720,7164500,0.0,0.0
2024-12-26 00:00:00-05:00,434.872143,436.714334,432.445641,433.911438,8194200,0.0,0.0
2024-12-27 00:00:00-05:00,430.435086,431.049140,422.264149,426.404083,18117700,0.0,0.0
2024-12-30 00:00:00-05:00,421.976951,423.452663,417.856814,420.758728,13158700,0.0,0.0
2024-12-31 00:00:00-05:00,422.016555,422.640522,416.628686,417.460632,13246500,0.0,0.0

Q4 Filter the dataframe to get the data of Mar 2023.

In [9]:
msft_mar_2023 = msft.loc['2023-03']
msft_mar_2023

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-03-01 00:00:00-05:00,244.958888,245.124953,240.103863,240.572769,27565300,0.0,0.0
2023-03-02 00:00:00-05:00,240.846290,245.584081,239.928034,245.300797,24808200,0.0,0.0
2023-03-03 00:00:00-05:00,246.355804,249.706447,245.574308,249.384079,30760100,0.0,0.0
2023-03-06 00:00:00-05:00,250.497697,254.102335,250.058111,250.927521,24109800,0.0,0.0
2023-03-07 00:00:00-05:00,250.370702,251.728560,247.528034,248.270447,21473200,0.0,0.0
2023-03-08 00:00:00-05:00,248.163018,248.651451,245.007745,247.830887,17340200,0.0,0.0
2023-03-09 00:00:00-05:00,249.901849,253.555318,245.759932,246.482819,26653400,0.0,0.0
2023-03-10 00:00:00-05:00,245.271451,246.941883,241.871963,242.839050,28333900,0.0,0.0
2023-03-13 00:00:00-04:00,241.676622,251.943492,240.045257,248.045792,33339700,0.0,0.0
2023-03-14 00:00:00-04:00,250.810335,255.030403,249.940925,254.756882,33620300,0.0,0.0
2023-03-15 00:00:00-04:00,253.965606,260.315235,253.213401,259.299286,46028000,0.0,0.0
2023-03-16 00:00:00-04:00,259.074617,270.162052,257.189273,269.810394,54768800,0.0,0.0
2023-03-17 00:00:00-04:00,271.822751,276.775439,269.927629,272.965668,69527400,0.0,0.0
2023-03-20 00:00:00-04:00,270.572334,271.060767,263.607275,265.932220,43466600,0.0,0.0
2023-03-21 00:00:00-04:00,268.520878,268.638097,263.284862,267.446320,34558700,0.0,0.0
2023-03-22 00:00:00-04:00,267.075121,274.538391,265.883343,265.990814,34873300,0.0,0.0
2023-03-23 00:00:00-04:00,271.510094,274.557910,268.833491,271.236572,36610900,0.0,0.0
2023-03-24 00:00:00-04:00,270.826304,274.137894,268.911655,274.079285,28172000,0.0,0.0
2023-03-27 00:00:00-04:00,274.010858,274.948641,269.146055,269.986176,26840200,0.0,0.0
2023-03-28 00:00:00-04:00,269.409835,269.751744,265.756337,268.862793,21878600,0.0,0.0
2023-03-29 00:00:00-04:00,272.506500,274.636091,271.969236,274.020660,25087000,0.0,0.0
2023-03-30 00:00:00-04:00,277.654588,277.879248,274.968207,277.478729,25053400,0.0,0.0
2023-03-31 00:00:00-04:00,277.166087,282.577901,276.452965,281.630341,32766000,0.0,0.0

Q5. 
- Create a new column "Intraday Price Change" where the value is Close price - Open price
- Create a new column "Price Change" where the value is Close price - last trading day Close price
- Create a new column "Percentage change" where the value is close price / last trading day close price - 1

In [10]:
msft['Intraday Price Change'] = msft['Close'] - msft['Open']
msft['Price Change'] = msft['Close'] - msft['Close'].shift(1)
msft['Percentage change'] = msft['Close'] / msft['Close'].shift(1) - 1

msft

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Intraday Price Change,Price Change,Percentage change
Date,,,,,,,,,,
2021-03-25 00:00:00-04:00,225.784364,227.358041,222.205211,222.944061,34061900,0.0,0.0,-2.840303,NaN,NaN
2021-03-26 00:00:00-04:00,222.186020,227.137350,222.186020,226.916641,25479900,0.0,0.0,4.730622,3.972580,0.017819
2021-03-29 00:00:00-04:00,227.022219,227.223733,222.502701,225.726822,25227500,0.0,0.0,-1.295397,-1.189819,-0.005243
2021-03-30 00:00:00-04:00,224.085945,224.393011,221.754223,222.473892,24792000,0.0,0.0,-1.612053,-3.252930,-0.014411
2021-03-31 00:00:00-04:00,223.491071,229.430748,222.992096,226.235413,43623500,0.0,0.0,2.744342,3.761520,0.016908
...,...,...,...,...,...,...,...,...,...,...
2026-03-18 00:00:00-04:00,397.130005,398.000000,391.000000,391.790009,25908500,0.0,0.0,-5.339996,-7.619995,-0.019078
2026-03-19 00:00:00-04:00,390.100006,392.489990,387.059998,389.019989,25138800,0.0,0.0,-1.080017,-2.770020,-0.007070
2026-03-20 00:00:00-04:00,386.790009,387.000000,380.119995,381.869995,50853200,0.0,0.0,-4.920013,-7.149994,-0.018380
2026-03-23 00:00:00-04:00,383.899994,387.209991,381.679993,383.000000,29680100,0.0,0.0,-0.899994,1.130005,0.002959
2026-03-24 00:00:00-04:00,382.410004,382.470001,371.850006,372.739990,40186581,0.0,0.0,-9.670013,-10.260010,-0.026789

Q6. Check whether there were any dividend within the data

In [11]:
has_dividend = (msft['Dividends'] > 0).any()
has_dividend

np.True_

Q7. Remove the column "Dividends" from the dataframe

In [12]:
msft = msft.drop(columns=['Dividends'])
msft

,Open,High,Low,Close,Volume,Stock Splits,Intraday Price Change,Price Change,Percentage change
Date,,,,,,,,,
2021-03-25 00:00:00-04:00,225.784364,227.358041,222.205211,222.944061,34061900,0.0,-2.840303,NaN,NaN
2021-03-26 00:00:00-04:00,222.186020,227.137350,222.186020,226.916641,25479900,0.0,4.730622,3.972580,0.017819
2021-03-29 00:00:00-04:00,227.022219,227.223733,222.502701,225.726822,25227500,0.0,-1.295397,-1.189819,-0.005243
2021-03-30 00:00:00-04:00,224.085945,224.393011,221.754223,222.473892,24792000,0.0,-1.612053,-3.252930,-0.014411
2021-03-31 00:00:00-04:00,223.491071,229.430748,222.992096,226.235413,43623500,0.0,2.744342,3.761520,0.016908
...,...,...,...,...,...,...,...,...,...
2026-03-18 00:00:00-04:00,397.130005,398.000000,391.000000,391.790009,25908500,0.0,-5.339996,-7.619995,-0.019078
2026-03-19 00:00:00-04:00,390.100006,392.489990,387.059998,389.019989,25138800,0.0,-1.080017,-2.770020,-0.007070
2026-03-20 00:00:00-04:00,386.790009,387.000000,380.119995,381.869995,50853200,0.0,-4.920013,-7.149994,-0.018380
2026-03-23 00:00:00-04:00,383.899994,387.209991,381.679993,383.000000,29680100,0.0,-0.899994,1.130005,0.002959
2026-03-24 00:00:00-04:00,382.410004,382.470001,371.850006,372.739990,40186581,0.0,-9.670013,-10.260010,-0.026789

Q8. Find the highest stock price ever in this period, and find the date of it

In [13]:
highest_price = msft['High'].max()
highest_price_date = msft['High'].idxmax()

highest_price, highest_price_date

(np.float64(552.2420017670738),
 Timestamp('2025-07-31 00:00:00-0400', tz='America/New_York'))

Q9. Find the highest volume date

In [14]:
highest_volume = msft['Volume'].max()
highest_volume_date = msft['Volume'].idxmax()

highest_volume_date, highest_volume

(Timestamp('2026-01-29 00:00:00-0500', tz='America/New_York'),
 np.int64(128855300))

Q10. Find the top 20 highest price percentage change date and it's percentage change, order in decending order.

In [15]:
highest_volume = msft['Volume'].max()
highest_volume_date = msft['Volume'].idxmax()

highest_volume_date, highest_volume

(Timestamp('2026-01-29 00:00:00-0500', tz='America/New_York'),
 np.int64(128855300))